name: expopharma
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  carousel_pro: ^1.0.0
  http: ^0.12.2
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  image_picker: ^0.6.7+22
  cloud_firestore: ^0.16.0+1
  firebase_database: ^6.0.0
  firebase_storage: ^7.0.0
  uuid: ^2.2.2
  badges: ^1.1.6
  carousel_slider: ^3.0.0
  flutter_typeahead: ^2.0.0
  flutter_barcode_scanner: ^1.0.1
  cached_network_image: ^2.5.0



dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/expopharma.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/drawer.jpg
   - images/bv.jpg
   - images/ph.jpg
   - images/cadu.jpg
   - images/labo/avene.png
   - images/labo/bioderma.jfif
   - images/labo/acm.png
   - images/labo/bo.jfif
   - images/labo/eye.png
   - images/labo/filor.png
   - images/labo/nore.jfif
   - images/labo/nux.jfif
   - images/labo/pf.png
   - images/labo/svr.png
   - images/labo/uri.jfif
   - images/labo/vichy.jpg
   - images/labo/nature.jpg
   - images/labo/lrp.png
   - images/labo/avene/avcima.jfif
   - images/labo/avene/avclex.jfif
   - images/labo/avene/avclge.jfif
   - images/labo/avene/aveath150.jfif
   - images/labo/avene/avecmi.jfif
   - images/categorie/bebe.jfif
   - images/categorie/dietetique.png
   - images/categorie/complements.jpg
   - images/categorie/cosmetique.png
   - images/categorie/login.jpg
   - images/categorie/medicament.jpg
   - images/categorie/orthopedie.jfif
   - images/categorie/pedicure.jpg
   - images/categorie/lab.jpg
   - images/categorie/alimentbebe.jfif
   - images/rsocial/f.png
   - images/cosmeto/antirid.jfif
   - images/cosmeto/blevre.jfif
   - images/cosmeto/crcicatrisante.jfif
   - images/cosmeto/crcorps.jfif
   - images/cosmeto/deo.jfif
   - images/cosmeto/ecran.jfif
   - images/cosmeto/geldouch.jfif
   - images/cosmeto/gelnet.jfif
   - images/cosmeto/huilchev.jfif
   - images/cosmeto/pigment.jfif
   - images/cosmeto/savon.jfif
   - images/cosmeto/crmains.jpg
   - images/cosmeto/crvisage.jpg
   - images/cosmeto/edt.jpg
   - images/cosmeto/shampo.jpg
   - images/cosmeto/crempieds.jpg
   - images/cosmeto/acne.jfif
   - images/expopharma.png






  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
